# --- Build React App ---
FROM node:18-alpine AS builder

WORKDIR /app

COPY client/package*.json ./
RUN npm install

COPY client/ .

ARG VITE_API_BASE_URL
ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}

RUN npm run build

# --- Serve with Nginx ---
FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

WORKDIR /var/www/html

COPY --from=builder /app/dist /var/www/html/public

RUN chmod -R 755 /var/www/html/public

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]